version: '3.8'
name: pruebadocker

services:
  db:
    #image: 975049981495.dkr.ecr.us-east-2.amazonaws.com/pruebaawsdocker:db-latest
    build: ./mySQL
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    ports:
      - "33068:3306"
    volumes:
      - "db_data:/var/lib/mysql"

  api:
    #image: 975049981495.dkr.ecr.us-east-2.amazonaws.com/pruebaawsdocker:api-latest
    build: ../api_docker/api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=blog_user
      - DB_NAME=blog_db
      - DB_PASSWORD=blog_password
    depends_on:
      - db

volumes:
  db_data: 
    driver: "local"
